name: "Github Deploy"
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Install dependencies
        run: pnpm i
      - name: Build
        run: pnpm build
      - name: Deploying...
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist